name: development

on:
  push:
    branches-ignore: [ main ]

jobs:
  build:
    name: pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up executables path
        run: |
          mkdir bin
          cd bin
          echo "$(pwd)" >> $GITHUB_PATH
