name: main

on:
  push:
    branches: [ main ]

env:
  SEMVERBOT_VERSION: "1.0.0"

jobs:
  build:
    name: pipeline
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: install pipenv
        run: |
          python3 -m pip install --upgrade poetry

      - name: cache python packages
        id: cache-python-packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: install python packages
        if: steps.cache-python-packages.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: set up path
        run: |
          mkdir bin
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: install semverbot
        run: |
          curl -o bin/sbot -L https://github.com/restechnica/semverbot/releases/download/v$SEMVERBOT_VERSION/sbot-linux-amd64
          chmod +x bin/sbot

      - name: update version
        run: |
          sbot update version
          echo "CURRENT_VERSION=$(sbot get version)" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$(sbot predict version)" >> $GITHUB_ENV
          echo "current version: $CURRENT_VERSION"
          echo "next version: $RELEASE_VERSION"
          poetry version $RELEASE_VERSION

      - name: build
        run: |
          poetry build

      - name: release version
        run: |
          sbot release version
          sbot push version

      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
